import { expect, test } from "@playwright/test";

async function startRanch(page: import("@playwright/test").Page): Promise<void> { await page.goto("/"); await expect(page.getByRole("heading", { name: "MOWBOT" })).toBeVisible(); await page.getByRole("button", { name: "Mow Lawn" }).first().click(); await expect(page.locator("canvas")).toBeVisible(); }

test("renders a playable lawn, moves the mower, updates coverage, and reaches results", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop", "Desktop interaction flow"); const errors: string[] = []; page.on("console", (message) => { if (message.type() === "error" && !message.text().includes("404")) errors.push(message.text()); }); await startRanch(page);
  await expect(page.getByText("Coverage")).toBeVisible(); await expect(page.getByRole("button", { name: "Stop mowing at dock" })).toBeVisible(); const canvas = page.locator("canvas"); const box = await canvas.boundingBox(); expect(box).not.toBeNull(); for (const [x, y] of [[0.5, 0.5], [0.48, 0.48], [0.52, 0.48], [0.5, 0.44]]) { await page.mouse.click(box!.x + box!.width * x, box!.y + box!.height * y); if (await page.locator(".inspection-card").isVisible()) break; } await expect(page.locator(".inspection-card")).toBeVisible(); await page.getByRole("button", { name: "Close inspection" }).click(); await canvas.screenshot({ path: testInfo.outputPath("ranch-world.png") }); const imageLength = await canvas.evaluate((node) => (node as HTMLCanvasElement).toDataURL().length); expect(imageLength).toBeGreaterThan(10_000);
  const before = await page.evaluate(() => window.__MOWBOT_DEBUG__?.mower()); await page.keyboard.down("w"); await page.waitForTimeout(900); await page.keyboard.up("w"); const after = await page.evaluate(() => window.__MOWBOT_DEBUG__?.mower()); expect(after?.z).not.toBe(before?.z); await page.keyboard.down("w"); await page.keyboard.down("ArrowLeft"); await page.waitForTimeout(250); await page.keyboard.up("ArrowLeft"); await page.keyboard.up("w"); const afterLeft = await page.evaluate(() => window.__MOWBOT_DEBUG__?.mower()); expect(afterLeft?.x).toBeGreaterThan(after!.x); await expect(page.locator("[data-hud=coverage]")).not.toHaveText("0.0%");
  await page.keyboard.press("Escape"); await expect(page.getByRole("heading", { name: "Paused" })).toBeVisible(); await page.evaluate(() => window.__MOWBOT_DEBUG__?.unlockAll()); await page.getByRole("button", { name: "Garage" }).click(); await expect(page.getByRole("heading", { name: "Garage" })).toBeVisible(); await expect(page.getByRole("heading", { name: "Dock station" })).toBeVisible(); await page.getByRole("button", { name: "Round Plaza" }).click(); await expect(page.getByRole("button", { name: "Round Plaza" })).toHaveClass(/selected/); await expect(page.locator(".dock-preview")).toHaveClass(/dock-round_plaza/); await page.getByRole("button", { name: "Wedge Aero" }).click(); await expect(page.locator(".mower-preview")).toHaveClass(/body-wedge_aero/); await page.getByRole("button", { name: "Long Range" }).click(); await expect(page.locator(".mower-preview")).toHaveClass(/battery-long_range/); await expect(page.locator(".preview-battery")).toBeVisible(); await page.getByRole("button", { name: "Wide Scan" }).click(); await expect(page.locator(".mower-preview")).toHaveClass(/sensor-wide_scan/); await expect(page.locator(".preview-lidar")).toBeVisible(); await page.getByRole("button", { name: "Hazard Ping" }).click(); await expect(page.locator(".mower-preview")).toHaveClass(/sensor-hazard_ping/); await expect(page.locator(".preview-side-light").first()).toBeVisible(); await page.getByRole("button", { name: "Back" }).click(); await page.getByRole("button", { name: "Mow Lawn" }).first().click(); await page.evaluate(() => window.__MOWBOT_DEBUG__?.collectible()); await expect(page.locator("[data-hud=parts]")).toHaveText("Parts 1 / 4"); await page.waitForFunction(() => localStorage.getItem("mowbot-save-v1")?.includes("color_safety_yellow")); await page.evaluate(() => window.__MOWBOT_DEBUG__?.complete()); await expect(page.getByText("LAWN COMPLETE")).toBeVisible(); await expect(page.getByRole("heading", { name: "Your Upgrades" })).toBeVisible(); await page.getByRole("button", { name: /Inspect/ }).first().click(); await expect(page.locator(".upgrade-modal")).toBeVisible(); expect(errors).toEqual([]); await page.screenshot({ path: testInfo.outputPath("ranch-results.png") });
});

test("returns the mower to the dock from the desktop HUD", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop", "Desktop dock return flow");
  await startRanch(page); await page.keyboard.down("w"); await page.waitForTimeout(900); await page.keyboard.up("w"); await page.getByRole("button", { name: "Return mower to dock" }).click(); await expect(page.locator("[data-hud=message]")).toHaveText("Returning to base");
});

test("shows the Arms garage bay and cargo telemetry", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop", "Desktop Arms flow");
  await page.goto("/"); await page.getByRole("button", { name: "Garage" }).click(); await expect(page.getByRole("heading", { name: "Arms" })).toBeVisible(); await expect(page.getByRole("button", { name: "Basic Claw" })).toBeVisible();
  await page.getByRole("button", { name: "Back to lawn select" }).click(); await page.getByRole("button", { name: "Mow Lawn" }).first().click(); await expect(page.locator("[data-hud=cargo]")).toHaveText("Cargo 0 / 1"); await expect(page.locator("[data-hud=terrain]")).toHaveText("Lawn clear");
});

test("can stop mowing from the dock and still shows the upgrade section", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop", "Desktop dock stop flow");
  await startRanch(page); await page.getByRole("button", { name: "Stop mowing at dock" }).click(); await expect(page.getByText("STOPPED AT DOCK")).toBeVisible(); await expect(page.getByRole("heading", { name: "Your Upgrades" })).toBeVisible();
});

test("starts every data-driven lawn", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "desktop", "Desktop level smoke flow");
  for (let index = 0; index < 5; index += 1) { await page.goto("/"); await page.getByRole("button", { name: "Mow Lawn" }).nth(index).click(); await expect(page.locator("canvas")).toBeVisible(); await expect(page.getByText("Coverage")).toBeVisible(); }
});

test("shows mobile touch controls and return dock action", async ({ page }, testInfo) => {
  test.skip(!testInfo.project.name.startsWith("mobile-"), "Mobile control check");
  await startRanch(page); const forward = page.getByRole("button", { name: "Drive forward" }); await expect(forward).toBeVisible(); await expect(page.getByRole("button", { name: "Drive backward" })).toBeVisible(); await expect(page.getByRole("button", { name: "Turn left" })).toBeVisible(); await expect(page.getByRole("button", { name: "Turn right" })).toBeVisible(); await expect(page.getByRole("button", { name: "Return mower to base" })).toBeVisible(); const before = await page.evaluate(() => window.__MOWBOT_DEBUG__?.mower()); const box = await forward.boundingBox(); expect(box).not.toBeNull(); await page.mouse.move(box!.x + box!.width / 2, box!.y + box!.height / 2); await page.mouse.down(); await page.waitForTimeout(300); await page.mouse.up(); const after = await page.evaluate(() => window.__MOWBOT_DEBUG__?.mower()); expect(after?.z).not.toBe(before?.z); await page.evaluate(() => window.__MOWBOT_DEBUG__?.hazard()); await page.getByRole("button", { name: "Return mower to base" }).click(); await expect(page.locator("[data-hud=message]")).toHaveText("Returning to base"); await page.screenshot({ path: testInfo.outputPath("mobile-controls.png") });
});
