import "./styles.css";
import "./touch.css";
import { levels } from "./data/levels";
import { getPartName, parts } from "./data/upgrades";
import { GameEngine } from "./engine";
import { InputManager } from "./input";
import { RapierPhysics } from "./physics";
import { IsometricRenderer } from "./renderer";
import { defaultSave, equip, loadSave, persistSave, unlockAll } from "./systems";
import type { EquippedLoadout, LawnInspection, Results, RunStatus, SaveData } from "./types";

declare global { interface Window { __MOWBOT_DEBUG__?: { complete: () => void; setBattery: (percent: number) => void; dock: () => void; hazard: () => void; collectible: () => void; treeDrop: () => void; unlockAll: () => void; resetSave: () => void; mower: () => { x: number; z: number } | null }; } }
const root = document.querySelector<HTMLDivElement>("#app")!; const debug = new URLSearchParams(location.search).has("debug");
let save: SaveData = loadSave(); let engine: GameEngine | null = null; let renderer: IsometricRenderer | null = null; let input: InputManager | null = null; let physics: RapierPhysics | null = null; let frame = 0; let settled = false; let syncedRunCollectibles = new Set<string>();
const escaped = (value: string) => value.replace(/[&<>"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[character]!);
const rankRecord = (id: string) => save.levelRecords[id];
const categoryLabels: Record<keyof EquippedLoadout, string> = { body: "Body shell", color: "Paint finish", mobility: "Mobility", deck: "Cutting deck", battery: "Battery", sensor: "Sensor", dock: "Dock station", arms: "Arms" };
function enableGarageReviewAccess(): void { if (!(import.meta as { env?: { DEV?: boolean } }).env?.DEV) return; save = unlockAll(save); persistSave(save); }
const partEntries = () => Object.entries(parts).flatMap(([category, items]) => items.map((part) => ({ category: category as keyof EquippedLoadout, part })));
const partRecord = (id: string) => partEntries().find((entry) => entry.part.id === id);
const safeClass = (id: string) => id.replace(/_/g, "-");
function robotLawnmowerLogo(modifier = ""): string {
  return `<svg class="robot-lawnmower-logo ${modifier}" viewBox="0 0 560 210" role="img" aria-label="Robot Lawnmower">
    <g class="logo-speed-lines" aria-hidden="true"><path d="M18 59h88M4 82h74M28 105h58"/><path class="logo-speed-accent" d="M445 172h91M466 188h70"/></g>
    <g class="logo-mowbot-marque"><path d="M128 4h205l24 26-24 26H128l-24-26z"/><text x="230" y="40" text-anchor="middle">MOWBOT</text><path d="M112 30H65M348 30h64"/></g>
    <g class="logo-robot-word"><text class="logo-word-outline" x="40" y="120">ROBOT</text><text class="logo-word-fill" x="40" y="120">ROBOT</text><path class="logo-gloss" d="M69 72c38-17 112-22 190-5"/></g>
    <g class="logo-lawnmower-word"><text class="logo-word-outline" x="42" y="176">LAWNMOWER</text><text class="logo-word-fill" x="42" y="176">LAWNMOWER</text></g>
    <path class="logo-underline" d="M70 190h366l34-14 50 14H438"/>
    <g class="logo-blade-badge" transform="translate(500 120) rotate(-12)" aria-hidden="true"><circle r="38"/><circle class="logo-blade-hub" r="9"/><path d="M-5-8c-22-22-22-34-11-42 11 11 18 23 17 43zm13 3c28-9 39-5 42 8-15 6-29 5-43-1zM-3 10c-6 29-15 37-28 32 0-16 5-29 17-40z"/></g>
  </svg>`;
}
function partEffect(id: string): string {
  const entry = partRecord(id); if (!entry) return "Garage cosmetic."; const part = entry.part as Record<string, string | number | boolean>;
  if (entry.category === "color") return `Paint finish: ${part.color}.`;
  if (entry.category === "body") return `Body shell. Turn handling x${Number(part.turn).toFixed(2)}.`;
  if (entry.category === "mobility") return `Mobility kit. Acceleration x${Number(part.acceleration).toFixed(2)}, turn x${Number(part.turn).toFixed(2)}.`;
  if (entry.category === "deck") return `Cutting deck. Cut radius x${Number(part.width).toFixed(2)}.`;
  if (entry.category === "battery") return `Battery pack. Capacity x${Number(part.capacity).toFixed(2)}, recharge x${Number(part.recharge).toFixed(2)}.`;
  if (entry.category === "sensor") return `Sensor package. Hazard reveal range x${Number(part.reveal).toFixed(2)}.`;
  if (entry.category === "arms") return `Pickup Arms. Carry ${Number(part.basketCapacity)} item${Number(part.basketCapacity) === 1 ? "" : "s"} with a ${Number(part.pickupRadius).toFixed(2)}m pickup radius.`;
  return "Dock station cosmetic for the charging base.";
}
function partModel(id: string, large = false): string { const entry = partRecord(id); const category = entry?.category ?? "body"; return `<span class="part-model ${large ? "part-model-large" : ""} part-model-${category} part-${safeClass(id)}" aria-hidden="true"><span></span><i></i><b></b></span>`; }
function collectedUnlockIds(run: GameEngine): string[] { return [...new Set(run.state.collectedThisRun.map((id) => run.level.collectibles.find((item) => item.id === id)?.unlockId).filter((id): id is string => Boolean(id)))]; }
function syncCollectedUnlocks(run: GameEngine): void {
  const newIds = run.state.collectedThisRun.filter((id) => !syncedRunCollectibles.has(id)); if (!newIds.length) return; newIds.forEach((id) => syncedRunCollectibles.add(id));
  const unlockIds = newIds.map((id) => run.level.collectibles.find((item) => item.id === id)?.unlockId).filter((id): id is string => Boolean(id)); if (!unlockIds.length) return;
  save = { ...save, garage: { ...save.garage, unlockedPartIds: [...new Set([...save.garage.unlockedPartIds, ...unlockIds])] } }; persistSave(save);
}

function stopGame(): void { cancelAnimationFrame(frame); input?.dispose(); input = null; renderer?.dispose(); renderer = null; physics?.dispose(); physics = null; engine = null; window.__MOWBOT_DEBUG__ = undefined; }
function selectScreen(): void {
  stopGame(); root.className = "screen-shell"; root.innerHTML = `<main class="level-select"><header class="brand-bar"><div class="brand-lockup">${robotLawnmowerLogo("logo-hero")}<h1 class="sr-only">MOWBOT</h1><p class="brand-division">AUTONOMOUS TURF DIVISION <span>// SEASON 01</span></p></div><button class="icon-command" data-action="garage" aria-label="Open garage" title="Garage"><span aria-hidden="true">⚙</span> Garage</button></header><section class="route-intro"><div><p class="eyebrow">CHOOSE YOUR CUT</p><h2>Pick a route</h2></div><p>Five lawns. One charged mower. Chase a clean line, save the flowerbeds, and bring every yard home.</p></section><section class="level-grid" aria-label="Select a lawn">${levels.map((level, index) => { const record = rankRecord(level.id); return `<article class="level-card" style="--level:${index}"><div class="level-card-top"><span class="level-number">ROUTE 0${index + 1}</span><span class="route-status">${record ? "CLEARED" : "OPEN"}</span></div><div class="level-card-copy"><h2>${escaped(level.name)}</h2><p>${escaped(level.description)}</p><div class="record-line"><span><small>RECORD</small>${record ? `Rank ${record.bestRank}` : "New route"}</span><span><small>BEST CUT</small>${record ? `${Math.round(record.bestCompletionPercent)}%` : `${level.collectibles.length} parts`}</span></div></div><button data-level="${level.id}"><span>Mow Lawn</span><b aria-hidden="true">→</b></button></article>`; }).join("")}</section></main>`;
  root.querySelector<HTMLButtonElement>("[data-action=garage]")!.onclick = garageScreen; root.querySelectorAll<HTMLButtonElement>("[data-level]").forEach((button) => { button.onclick = () => startGame(button.dataset.level!); });
}
function garageScreen(): void {
  stopGame(); enableGarageReviewAccess(); root.className = "screen-shell garage-screen"; const equipped = save.garage.equipped; const stats = new GameEngine("ranch-house", equipped).stats; const categories = Object.keys(parts) as (keyof EquippedLoadout)[];
  root.innerHTML = `<main class="garage"><header class="brand-bar garage-brand-bar"><div class="garage-heading">${robotLawnmowerLogo("logo-section")}<div><p class="eyebrow">CONFIGURATION BAY</p><h1>Garage</h1><p class="garage-subtitle">Tune the machine. Own the lawn.</p></div></div><button class="icon-command" data-action="back" aria-label="Back to lawn select" title="Back"><span aria-hidden="true">←</span> Back</button></header><section class="garage-main"><div class="mower-preview" style="--mower-color:${stats.color}"><div class="preview-deck"></div><div class="preview-shell"></div><div class="preview-glass"></div><i></i><i></i></div><div class="garage-stats"><p class="eyebrow">LIVE TELEMETRY</p><h2>Current Output</h2><dl><div><dt>Speed</dt><dd>${stats.maxSpeed.toFixed(1)}</dd></div><div><dt>Cut radius</dt><dd>${stats.deckRadius.toFixed(2)}</dd></div><div><dt>Battery</dt><dd>${Math.round(stats.capacity)}</dd></div><div><dt>Sensor</dt><dd>${stats.sensorRadius.toFixed(1)}</dd></div></dl></div></section><div class="bay-divider"><span>UPGRADE BAYS</span></div><section class="part-bays">${categories.map((category, index) => `<section class="part-bay" style="--bay:${index}"><h2>${category}</h2><div class="part-options">${parts[category].map((part) => { const unlocked = save.garage.unlockedPartIds.includes(part.id); const equipped = save.garage.equipped[category] === part.id; return `<button class="part-option ${equipped ? "selected" : ""}" data-category="${category}" data-part="${part.id}" ${unlocked ? "" : "disabled"}><span>${escaped(part.name)}</span><small>${equipped ? "EQUIPPED" : unlocked ? "AVAILABLE" : "LOCKED"}</small></button>`; }).join("")}</div></section>`).join("")}</section></main>`;
  const main = root.querySelector<HTMLElement>(".garage-main")!; const mowerPreview = root.querySelector<HTMLElement>(".mower-preview")!; mowerPreview.classList.add(`body-${equipped.body.replace("body_", "")}`, `mobility-${equipped.mobility.replace("mobility_", "")}`, `deck-${equipped.deck.replace("deck_", "")}`, `battery-${equipped.battery.replace("battery_", "")}`, `sensor-${equipped.sensor.replace("sensor_", "")}`); const batteryDetail = document.createElement("div"); batteryDetail.className = "preview-battery"; batteryDetail.setAttribute("aria-hidden", "true"); const sensorDetail = document.createElement("div"); sensorDetail.className = "preview-sensor"; sensorDetail.setAttribute("aria-hidden", "true"); const lidarDetail = document.createElement("div"); lidarDetail.className = "preview-lidar"; lidarDetail.setAttribute("aria-hidden", "true"); const leftLight = document.createElement("div"); leftLight.className = "preview-side-light preview-side-light-left"; leftLight.setAttribute("aria-hidden", "true"); const rightLight = document.createElement("div"); rightLight.className = "preview-side-light preview-side-light-right"; rightLight.setAttribute("aria-hidden", "true"); mowerPreview.append(batteryDetail, sensorDetail, lidarDetail, leftLight, rightLight); const showcase = document.createElement("section"); showcase.className = "garage-showcase"; const dockPreview = document.createElement("div"); dockPreview.className = `dock-preview dock-${equipped.dock.replace("dock_", "")}`; dockPreview.setAttribute("aria-label", "Dock preview"); dockPreview.innerHTML = `<div class="dock-preview-pad"></div><div class="dock-preview-inset"></div><div class="dock-preview-beacon"></div><div class="dock-preview-canopy"></div>`; showcase.append(mowerPreview, dockPreview); main.prepend(showcase); root.querySelectorAll<HTMLElement>(".part-bay h2").forEach((heading, index) => { heading.textContent = categoryLabels[categories[index]]; });
  root.querySelector<HTMLElement>(".mower-preview")!.classList.add(`arms-${equipped.arms.replace("arms_", "")}`); root.querySelector<HTMLButtonElement>("[data-action=back]")!.onclick = selectScreen; root.querySelectorAll<HTMLButtonElement>("[data-category]").forEach((button) => { button.onclick = () => { save = equip(save, button.dataset.category as keyof EquippedLoadout, button.dataset.part!); persistSave(save); garageScreen(); }; });
}
function hudMarkup(): string { return `<div class="hud-top"><div class="hud-brand">${robotLawnmowerLogo("logo-hud")}</div><section class="hud-readout coverage-readout"><span>Coverage</span><strong data-hud="coverage">0.0%</strong></section><section class="hud-readout battery-readout"><span>Battery</span><strong data-hud="battery">100%</strong><i class="meter"><b data-hud="battery-fill"></b></i></section><section class="hud-readout score-readout"><span>Score</span><strong data-hud="score">0</strong><small data-hud="multiplier">x1.00</small></section><section class="hud-readout strike-readout"><span>Strikes</span><strong data-hud="strikes">3 / 3</strong></section><button class="pause-command" data-action="pause" aria-label="Pause game" title="Pause"><span aria-hidden="true">Ⅱ</span><b>Pause</b></button></div><button class="dock-stop-command" data-action="stop-mowing" aria-label="Stop mowing at dock">Stop mowing?</button><div class="hud-bottom"><span class="status-chip" data-hud="timer">00:00</span><span class="status-chip" data-hud="parts">Parts 0</span><span class="status-chip" data-hud="cargo">Cargo 0 / 1</span><span class="status-chip" data-hud="terrain">Lawn clear</span><span class="message" data-hud="message">Docked and ready</span></div><div class="touch-controls" aria-label="Touch controls"><button class="touch-return" data-touch="return" aria-label="Return mower to base"><span aria-hidden="true">↶</span> Return</button><div class="touch-pad" aria-label="Drive mower"><button class="touch-direction touch-up" data-touch-direction="up" aria-label="Drive forward">▲</button><button class="touch-direction touch-left" data-touch-direction="left" aria-label="Turn left">◀</button><button class="touch-direction touch-right" data-touch-direction="right" aria-label="Turn right">▶</button><button class="touch-direction touch-down" data-touch-direction="down" aria-label="Drive backward">▼</button></div></div>${debug ? `<div class="debug-panel"><button data-debug="complete">Complete</button><button data-debug="hazard">Hazard</button><button data-debug="battery">Battery 0</button><button data-debug="part">Part</button><button data-debug="tree">Tree drop</button></div>` : ""}`; }
function ensureDockReturnButton(): void {
  const button = document.createElement("button");
  button.className = "dock-return-command";
  button.type = "button";
  button.dataset.action = "return-dock";
  button.setAttribute("aria-label", "Return mower to dock");
  button.innerHTML = `<span aria-hidden="true">↶</span><b>Return to Dock</b>`;
  button.onclick = () => engine?.returnToDock();
  root.querySelector<HTMLElement>(".hud")?.append(button);
}
function startGame(levelId: string): void {
  stopGame(); settled = false; syncedRunCollectibles = new Set(); engine = new GameEngine(levelId, save.garage.equipped); input = new InputManager(); physics = new RapierPhysics(); void physics.initialize(engine.level).catch(() => undefined); root.className = "game-root"; root.innerHTML = `<div class="scene-host"></div><div class="hud">${hudMarkup()}</div>`; renderer = new IsometricRenderer(root.querySelector<HTMLDivElement>(".scene-host")!, engine); bindGameUi(); exposeDebug(); updateHud(); let previous = performance.now();
  const loop = (now: number) => { if (!engine || !renderer || !input) return; const controls = input.read(); if (controls.pause) pauseOverlay(); else { engine.tick(controls, (now - previous) / 1000); syncCollectedUnlocks(engine); renderer.sync(); updateHud(); if (["complete", "failed", "stopped"].includes(engine.state.status)) finishRun(); } previous = now; frame = requestAnimationFrame(loop); }; frame = requestAnimationFrame(loop);
}
function bindGameUi(): void {
  ensureDockReturnButton();
  root.querySelector<HTMLButtonElement>("[data-action=pause]")!.onclick = pauseOverlay;
  root.querySelector<HTMLButtonElement>("[data-action=stop-mowing]")!.onclick = () => engine?.stopMowingAtDock();
  root.querySelector<HTMLCanvasElement>("canvas")!.onclick = (event) => { const info = renderer?.inspectAt(event.clientX, event.clientY); if (info) showInspection(info); };
  const returnButton = root.querySelector<HTMLButtonElement>("[data-touch=return]")!;
  const pointers = new Map<number, string>();
  const direction = { up: { x: 0, y: -1 }, down: { x: 0, y: 1 }, left: { x: -1, y: 0 }, right: { x: 1, y: 0 } } as const;
  const syncDirections = () => { const pressed = [...pointers.values()].map((name) => direction[name as keyof typeof direction]); input?.setTouch(Math.max(-1, Math.min(1, pressed.reduce((sum, value) => sum + value.x, 0))), Math.max(-1, Math.min(1, pressed.reduce((sum, value) => sum + value.y, 0))), 0); };
  root.querySelectorAll<HTMLButtonElement>("[data-touch-direction]").forEach((button) => {
    const release = (event: PointerEvent) => { if (pointers.delete(event.pointerId)) syncDirections(); };
    button.onpointerdown = (event) => { event.preventDefault(); pointers.set(event.pointerId, button.dataset.touchDirection!); button.setPointerCapture(event.pointerId); engine?.cancelReturnToDock(); syncDirections(); };
    button.onpointerup = release; button.onpointercancel = release; button.onlostpointercapture = release;
  });
  returnButton.onclick = () => engine?.returnToDock();
  root.querySelectorAll<HTMLButtonElement>("[data-debug]").forEach((button) => { button.onclick = () => { if (button.dataset.debug === "complete") engine?.debug.complete(); if (button.dataset.debug === "hazard") engine?.debug.teleportToHazard(); if (button.dataset.debug === "battery") engine?.debug.setBatteryPercent(0); if (button.dataset.debug === "part") engine?.debug.teleportToCollectible(); if (button.dataset.debug === "tree") engine?.debug.bumpTreeDrop(); }; });
}
function updateHud(): void { if (!engine) return; const state = engine.state; const value = (name: string) => root.querySelector<HTMLElement>(`[data-hud=${name}]`)!; value("coverage").textContent = `${state.completionPercent.toFixed(1)}%`; value("battery").textContent = `${Math.round(state.batteryEnergy / state.batteryCapacity * 100)}%`; value("battery-fill").style.width = `${Math.max(0, state.batteryEnergy / state.batteryCapacity * 100)}%`; value("score").textContent = state.score.toLocaleString(); value("multiplier").textContent = `x${state.multiplier.toFixed(2)}`; value("strikes").textContent = `${state.strikesRemaining} / 3`; value("timer").textContent = `${String(Math.floor(state.elapsedSeconds / 60)).padStart(2, "0")}:${String(Math.floor(state.elapsedSeconds % 60)).padStart(2, "0")}`; value("parts").textContent = `Parts ${state.collectedThisRun.length} / ${engine.level.collectibles.length}`; value("cargo").textContent = `Cargo ${state.carriedItems.length} / ${engine.stats.basketCapacity}`; const patch = engine.currentTallGrass; value("terrain").textContent = patch ? `Tall ${engine.currentTallGrassPasses}/${patch.passesRequired}` : "Lawn clear"; value("message").textContent = state.message; root.querySelector<HTMLButtonElement>("[data-action=stop-mowing]")!.classList.toggle("visible", engine.isAtDock && state.status === "playing"); }
function showInspection(info: LawnInspection): void { root.querySelector(".inspection-card")?.remove(); const card = document.createElement("aside"); card.className = "inspection-card"; card.innerHTML = `<div class="inspection-model ${escaped(info.visual)}" aria-hidden="true"><span></span><i></i><b></b></div><p class="eyebrow">${escaped(info.model)}</p><h2>${escaped(info.name)}</h2><p>${escaped(info.detail)}</p><button class="inspection-close" aria-label="Close inspection">X</button>`; card.querySelector<HTMLButtonElement>(".inspection-close")!.onclick = () => card.remove(); root.append(card); }
function pauseOverlay(): void { if (!engine || engine.state.status !== "playing") return; engine.setPaused(true); const overlay = document.createElement("div"); overlay.className = "pause-overlay"; overlay.innerHTML = `<section class="pause-menu">${robotLawnmowerLogo("logo-overlay")}<div class="pause-title"><p class="eyebrow">MOWER IDLE // ROUTE ON HOLD</p><h2>Paused</h2></div><button class="pause-primary" data-pause="resume"><span>Resume</span><b aria-hidden="true">→</b></button><button data-pause="restart">Restart Lawn</button><button data-pause="garage">Garage</button><button data-pause="select">Level Select</button><p class="pause-tip">TIP: Hold a clean line to keep your score multiplier climbing.</p></section>`; root.append(overlay); overlay.querySelector<HTMLButtonElement>("[data-pause=resume]")!.onclick = () => { engine?.setPaused(false); overlay.remove(); }; overlay.querySelector<HTMLButtonElement>("[data-pause=restart]")!.onclick = () => startGame(engine!.level.id); overlay.querySelector<HTMLButtonElement>("[data-pause=garage]")!.onclick = garageScreen; overlay.querySelector<HTMLButtonElement>("[data-pause=select]")!.onclick = selectScreen; }
function finishRun(): void { if (!engine || settled) return; settled = true; const run = engine; const result = run.results!; const existing = save.levelRecords[run.level.id]; const unlocks = collectedUnlockIds(run); save = { ...save, garage: { ...save.garage, unlockedPartIds: [...new Set([...save.garage.unlockedPartIds, ...unlocks])] }, levelRecords: { ...save.levelRecords, [run.level.id]: { bestScore: Math.max(existing?.bestScore ?? 0, result.score), bestRank: existing && existing.bestScore > result.score ? existing.bestRank : result.rank, bestCompletionPercent: Math.max(existing?.bestCompletionPercent ?? 0, result.completion), bestTimeSeconds: !existing?.bestTimeSeconds || result.time < existing.bestTimeSeconds ? result.time : existing.bestTimeSeconds, collectiblesFound: [...new Set([...(existing?.collectiblesFound ?? []), ...run.state.collectedThisRun])] } } }; persistSave(save); setTimeout(() => resultsScreen(run.level.name, result, run.state.status, unlocks), 220); }
function resultsScreen(name: string, result: Results, status: RunStatus, unlocks: string[]): void {
  stopGame(); root.className = "screen-shell results-screen"; const failed = status === "failed"; const eyebrow = failed ? "ROUTE ENDED" : status === "stopped" ? "STOPPED AT DOCK" : "LAWN COMPLETE";
  root.innerHTML = `<main class="results">${robotLawnmowerLogo("logo-results")}<div class="result-heading"><p class="eyebrow">${eyebrow}</p><h1>${failed ? "System Halt" : result.rank}</h1><h2>${escaped(name)}</h2></div><section class="results-grid"><div><span>Score</span><strong>${result.score.toLocaleString()}</strong></div><div><span>Coverage</span><strong>${result.completion.toFixed(1)}%</strong></div><div><span>Time</span><strong>${Math.round(result.time)}s</strong></div><div><span>Strikes</span><strong>${result.strikes}</strong></div><div><span>Battery</span><strong>${Math.round(result.battery)}%</strong></div><div><span>Parts</span><strong>${result.collectibles}</strong></div></section><section class="upgrade-results"><h2>Your Upgrades</h2>${unlocks.length ? `<div class="upgrade-gallery">${unlocks.map((id) => `<button class="upgrade-card" data-upgrade="${id}" aria-label="Inspect ${escaped(getPartName(id))}">${partModel(id)}<strong>${escaped(getPartName(id))}</strong></button>`).join("")}</div>` : `<p>No upgrade parts recovered this run.</p>`}</section><div class="result-actions"><button class="result-primary" data-action="retry">${failed ? "Restart Lawn" : "Mow Again"}</button><button data-action="garage">Garage</button><button data-action="select">Level Select</button></div></main>`;
  root.querySelector<HTMLButtonElement>("[data-action=retry]")!.onclick = () => startGame(levels.find((level) => level.name === name)?.id ?? "ranch-house"); root.querySelector<HTMLButtonElement>("[data-action=garage]")!.onclick = garageScreen; root.querySelector<HTMLButtonElement>("[data-action=select]")!.onclick = selectScreen; root.querySelectorAll<HTMLButtonElement>("[data-upgrade]").forEach((button) => { button.onclick = () => showUpgradeModal(button.dataset.upgrade!); });
}
function showUpgradeModal(id: string): void { root.querySelector(".upgrade-modal")?.remove(); const modal = document.createElement("aside"); modal.className = "upgrade-modal"; modal.innerHTML = `<div class="upgrade-modal-card">${partModel(id, true)}<p class="eyebrow">${escaped(categoryLabels[partRecord(id)?.category ?? "body"])}</p><h2>${escaped(getPartName(id))}</h2><p>${escaped(partEffect(id))}</p><button class="inspection-close upgrade-close" aria-label="Close upgrade details">X</button></div>`; modal.querySelector<HTMLButtonElement>(".upgrade-close")!.onclick = () => modal.remove(); root.append(modal); }
function exposeDebug(): void { window.__MOWBOT_DEBUG__ = { complete: () => engine?.debug.complete(), setBattery: (percent) => engine?.debug.setBatteryPercent(percent), dock: () => engine?.debug.teleportToDock(), hazard: () => engine?.debug.teleportToHazard(), collectible: () => engine?.debug.teleportToCollectible(), treeDrop: () => engine?.debug.bumpTreeDrop(), unlockAll: () => { save = unlockAll(save); persistSave(save); }, resetSave: () => { save = defaultSave(); persistSave(save); }, mower: () => engine ? { ...engine.mower.position } : null }; }
selectScreen();
