import "./styles.css";
import "./touch.css";
import { levels } from "./data/levels";
import { getPartName, parts } from "./data/upgrades";
import { GameEngine } from "./engine";
import { InputManager } from "./input";
import { RapierPhysics } from "./physics";
import { IsometricRenderer } from "./renderer";
import { defaultSave, equip, loadSave, persistSave, unlockAll } from "./systems";
import type { EquippedLoadout, Results, SaveData } from "./types";

declare global { interface Window { __MOWBOT_DEBUG__?: { complete: () => void; setBattery: (percent: number) => void; dock: () => void; hazard: () => void; unlockAll: () => void; resetSave: () => void; mower: () => { x: number; z: number } | null }; } }
const root = document.querySelector<HTMLDivElement>("#app")!; const debug = new URLSearchParams(location.search).has("debug");
let save: SaveData = loadSave(); let engine: GameEngine | null = null; let renderer: IsometricRenderer | null = null; let input: InputManager | null = null; let physics: RapierPhysics | null = null; let frame = 0; let settled = false;
const escaped = (value: string) => value.replace(/[&<>"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[character]!);
const rankRecord = (id: string) => save.levelRecords[id];

function stopGame(): void { cancelAnimationFrame(frame); input?.dispose(); input = null; renderer?.dispose(); renderer = null; physics?.dispose(); physics = null; engine = null; window.__MOWBOT_DEBUG__ = undefined; }
function selectScreen(): void {
  stopGame(); root.className = "screen-shell"; root.innerHTML = `<main class="level-select"><header class="brand-bar"><div><p class="eyebrow">AUTONOMOUS TURF DIVISION</p><h1>MOWBOT</h1></div><button class="icon-command" data-action="garage" aria-label="Open garage" title="Garage">Garage</button></header><section class="level-grid" aria-label="Select a lawn">${levels.map((level, index) => { const record = rankRecord(level.id); return `<article class="level-card" style="--level:${index}"><div class="level-number">0${index + 1}</div><div><h2>${escaped(level.name)}</h2><p>${escaped(level.description)}</p><div class="record-line"><span>${record ? `Rank ${record.bestRank}` : "New route"}</span><span>${record ? `${Math.round(record.bestCompletionPercent)}% best` : `${level.collectibles.length} parts`}</span></div></div><button data-level="${level.id}">Mow Lawn</button></article>`; }).join("")}</section></main>`;
  root.querySelector<HTMLButtonElement>("[data-action=garage]")!.onclick = garageScreen; root.querySelectorAll<HTMLButtonElement>("[data-level]").forEach((button) => { button.onclick = () => startGame(button.dataset.level!); });
}
function garageScreen(): void {
  stopGame(); root.className = "screen-shell garage-screen"; const stats = new GameEngine("ranch-house", save.garage.equipped).stats; const categories = Object.keys(parts) as (keyof EquippedLoadout)[];
  root.innerHTML = `<main class="garage"><header class="brand-bar"><div><p class="eyebrow">CONFIGURATION BAY</p><h1>Garage</h1></div><button class="icon-command" data-action="back" aria-label="Back to lawn select" title="Back">Back</button></header><section class="garage-main"><div class="mower-preview" style="--mower-color:${stats.color}"><div class="preview-deck"></div><div class="preview-shell"></div><div class="preview-glass"></div><i></i><i></i></div><div class="garage-stats"><h2>Current Output</h2><dl><div><dt>Speed</dt><dd>${stats.maxSpeed.toFixed(1)}</dd></div><div><dt>Cut radius</dt><dd>${stats.deckRadius.toFixed(2)}</dd></div><div><dt>Battery</dt><dd>${Math.round(stats.capacity)}</dd></div><div><dt>Sensor</dt><dd>${stats.sensorRadius.toFixed(1)}</dd></div></dl></div></section><section class="part-bays">${categories.map((category) => `<section class="part-bay"><h2>${category}</h2><div class="part-options">${parts[category].map((part) => { const unlocked = save.garage.unlockedPartIds.includes(part.id); const equipped = save.garage.equipped[category] === part.id; return `<button class="part-option ${equipped ? "selected" : ""}" data-category="${category}" data-part="${part.id}" ${unlocked ? "" : "disabled"}>${escaped(part.name)}${unlocked ? "" : " Locked"}</button>`; }).join("")}</div></section>`).join("")}</section></main>`;
  root.querySelector<HTMLButtonElement>("[data-action=back]")!.onclick = selectScreen; root.querySelectorAll<HTMLButtonElement>("[data-category]").forEach((button) => { button.onclick = () => { save = equip(save, button.dataset.category as keyof EquippedLoadout, button.dataset.part!); persistSave(save); garageScreen(); }; });
}
function hudMarkup(): string { return `<div class="hud-top"><section class="hud-readout"><span>Coverage</span><strong data-hud="coverage">0.0%</strong></section><section class="hud-readout"><span>Battery</span><strong data-hud="battery">100%</strong><i class="meter"><b data-hud="battery-fill"></b></i></section><section class="hud-readout"><span>Score</span><strong data-hud="score">0</strong><small data-hud="multiplier">x1.00</small></section><section class="hud-readout strike-readout"><span>Strikes</span><strong data-hud="strikes">3 / 3</strong></section><button class="pause-command" data-action="pause" aria-label="Pause game" title="Pause">Pause</button></div><div class="hud-bottom"><span data-hud="timer">00:00</span><span data-hud="parts">Parts 0</span><span class="message" data-hud="message">Docked and ready</span></div><div class="touch-controls" aria-label="Touch controls"><button class="touch-return" data-touch="return" aria-label="Return mower to base">Return</button><div class="touch-pad" aria-label="Drive mower"><button class="touch-direction touch-up" data-touch-direction="up" aria-label="Drive forward">^</button><button class="touch-direction touch-left" data-touch-direction="left" aria-label="Turn left">&lt;</button><button class="touch-direction touch-right" data-touch-direction="right" aria-label="Turn right">&gt;</button><button class="touch-direction touch-down" data-touch-direction="down" aria-label="Drive backward">v</button></div></div>${debug ? `<div class="debug-panel"><button data-debug="complete">Complete</button><button data-debug="hazard">Hazard</button><button data-debug="battery">Battery 0</button></div>` : ""}`; }
function startGame(levelId: string): void {
  stopGame(); settled = false; engine = new GameEngine(levelId, save.garage.equipped); input = new InputManager(); physics = new RapierPhysics(); void physics.initialize(engine.level).catch(() => undefined); root.className = "game-root"; root.innerHTML = `<div class="scene-host"></div><div class="hud">${hudMarkup()}</div>`; renderer = new IsometricRenderer(root.querySelector<HTMLDivElement>(".scene-host")!, engine); bindGameUi(); exposeDebug(); let previous = performance.now();
  const loop = (now: number) => { if (!engine || !renderer || !input) return; const controls = input.read(); if (controls.pause) pauseOverlay(); else { engine.tick(controls, (now - previous) / 1000); renderer.sync(); updateHud(); if (engine.state.status === "complete" || engine.state.status === "failed") finishRun(); } previous = now; frame = requestAnimationFrame(loop); }; frame = requestAnimationFrame(loop);
}
function bindGameUi(): void {
  root.querySelector<HTMLButtonElement>("[data-action=pause]")!.onclick = pauseOverlay;
  const returnButton = root.querySelector<HTMLButtonElement>("[data-touch=return]")!;
  const pointers = new Map<number, string>();
  const direction = { up: { x: 0, y: -1 }, down: { x: 0, y: 1 }, left: { x: -1, y: 0 }, right: { x: 1, y: 0 } } as const;
  const syncDirections = () => { const pressed = [...pointers.values()].map((name) => direction[name as keyof typeof direction]); input?.setTouch(Math.max(-1, Math.min(1, pressed.reduce((sum, value) => sum + value.x, 0))), Math.max(-1, Math.min(1, pressed.reduce((sum, value) => sum + value.y, 0))), 0); };
  root.querySelectorAll<HTMLButtonElement>("[data-touch-direction]").forEach((button) => {
    const release = (event: PointerEvent) => { if (pointers.delete(event.pointerId)) syncDirections(); };
    button.onpointerdown = (event) => { event.preventDefault(); pointers.set(event.pointerId, button.dataset.touchDirection!); button.setPointerCapture(event.pointerId); engine?.cancelReturnToDock(); syncDirections(); };
    button.onpointerup = release; button.onpointercancel = release; button.onlostpointercapture = release;
  });
  returnButton.onclick = () => engine?.returnToDock();
  root.querySelectorAll<HTMLButtonElement>("[data-debug]").forEach((button) => { button.onclick = () => { if (button.dataset.debug === "complete") engine?.debug.complete(); if (button.dataset.debug === "hazard") engine?.debug.teleportToHazard(); if (button.dataset.debug === "battery") engine?.debug.setBatteryPercent(0); }; });
}
function updateHud(): void { if (!engine) return; const state = engine.state; const value = (name: string) => root.querySelector<HTMLElement>(`[data-hud=${name}]`)!; value("coverage").textContent = `${state.completionPercent.toFixed(1)}%`; value("battery").textContent = `${Math.round(state.batteryEnergy / state.batteryCapacity * 100)}%`; value("battery-fill").style.width = `${Math.max(0, state.batteryEnergy / state.batteryCapacity * 100)}%`; value("score").textContent = state.score.toLocaleString(); value("multiplier").textContent = `x${state.multiplier.toFixed(2)}`; value("strikes").textContent = `${state.strikesRemaining} / 3`; value("timer").textContent = `${String(Math.floor(state.elapsedSeconds / 60)).padStart(2, "0")}:${String(Math.floor(state.elapsedSeconds % 60)).padStart(2, "0")}`; value("parts").textContent = `Parts ${state.collectedThisRun.length} / ${engine.level.collectibles.length}`; value("message").textContent = state.message; }
function pauseOverlay(): void { if (!engine || engine.state.status !== "playing") return; engine.setPaused(true); const overlay = document.createElement("div"); overlay.className = "pause-overlay"; overlay.innerHTML = `<section class="pause-menu"><p class="eyebrow">MOWER IDLE</p><h2>Paused</h2><button data-pause="resume">Resume</button><button data-pause="restart">Restart Lawn</button><button data-pause="garage">Garage</button><button data-pause="select">Level Select</button></section>`; root.append(overlay); overlay.querySelector<HTMLButtonElement>("[data-pause=resume]")!.onclick = () => { engine?.setPaused(false); overlay.remove(); }; overlay.querySelector<HTMLButtonElement>("[data-pause=restart]")!.onclick = () => startGame(engine!.level.id); overlay.querySelector<HTMLButtonElement>("[data-pause=garage]")!.onclick = garageScreen; overlay.querySelector<HTMLButtonElement>("[data-pause=select]")!.onclick = selectScreen; }
function finishRun(): void { if (!engine || settled) return; settled = true; const run = engine; const result = run.results!; const existing = save.levelRecords[run.level.id]; const unlocks = run.level.collectibles.filter((item) => run.collectibles.has(item.id)).map((item) => item.unlockId); save = { ...save, garage: { ...save.garage, unlockedPartIds: [...new Set([...save.garage.unlockedPartIds, ...unlocks])] }, levelRecords: { ...save.levelRecords, [run.level.id]: { bestScore: Math.max(existing?.bestScore ?? 0, result.score), bestRank: existing && existing.bestScore > result.score ? existing.bestRank : result.rank, bestCompletionPercent: Math.max(existing?.bestCompletionPercent ?? 0, result.completion), bestTimeSeconds: !existing?.bestTimeSeconds || result.time < existing.bestTimeSeconds ? result.time : existing.bestTimeSeconds, collectiblesFound: [...new Set([...(existing?.collectiblesFound ?? []), ...run.state.collectedThisRun])] } } }; persistSave(save); setTimeout(() => resultsScreen(run.level.name, result, run.state.status === "failed", unlocks), 220); }
function resultsScreen(name: string, result: Results, failed: boolean, unlocks: string[]): void { stopGame(); root.className = "screen-shell results-screen"; root.innerHTML = `<main class="results"><p class="eyebrow">${failed ? "ROUTE ENDED" : "LAWN COMPLETE"}</p><h1>${failed ? "System Halt" : result.rank}</h1><h2>${escaped(name)}</h2><section class="results-grid"><div><span>Score</span><strong>${result.score.toLocaleString()}</strong></div><div><span>Coverage</span><strong>${result.completion.toFixed(1)}%</strong></div><div><span>Time</span><strong>${Math.round(result.time)}s</strong></div><div><span>Strikes</span><strong>${result.strikes}</strong></div><div><span>Battery</span><strong>${Math.round(result.battery)}%</strong></div><div><span>Parts</span><strong>${result.collectibles}</strong></div></section>${unlocks.length ? `<p class="unlocks">Unlocked: ${unlocks.map(getPartName).join(", ")}</p>` : ""}<div class="result-actions"><button data-action="retry">${failed ? "Restart Lawn" : "Mow Again"}</button><button data-action="garage">Garage</button><button data-action="select">Level Select</button></div></main>`; root.querySelector<HTMLButtonElement>("[data-action=retry]")!.onclick = () => startGame(levels.find((level) => level.name === name)?.id ?? "ranch-house"); root.querySelector<HTMLButtonElement>("[data-action=garage]")!.onclick = garageScreen; root.querySelector<HTMLButtonElement>("[data-action=select]")!.onclick = selectScreen; }
function exposeDebug(): void { window.__MOWBOT_DEBUG__ = { complete: () => engine?.debug.complete(), setBattery: (percent) => engine?.debug.setBatteryPercent(percent), dock: () => engine?.debug.teleportToDock(), hazard: () => engine?.debug.teleportToHazard(), unlockAll: () => { save = unlockAll(save); persistSave(save); }, resetSave: () => { save = defaultSave(); persistSave(save); }, mower: () => engine ? { ...engine.mower.position } : null }; }
selectScreen();
