import * as THREE from "three";
import { GameEngine } from "./engine";
import { GrassCellState } from "./systems";

type MaterialMesh = THREE.Mesh<THREE.BufferGeometry, THREE.MeshStandardMaterial>;
const material = (color: string, roughness = 0.85) => new THREE.MeshStandardMaterial({ color, roughness, flatShading: true });
const mesh = (geometry: THREE.BufferGeometry, color: string) => new THREE.Mesh(geometry, material(color));
const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value));

export class IsometricRenderer {
  readonly scene = new THREE.Scene(); readonly renderer: THREE.WebGLRenderer; readonly camera: THREE.OrthographicCamera; readonly mower = new THREE.Group();
  private grassTexture!: THREE.CanvasTexture; private grassContext!: CanvasRenderingContext2D; private grassImage!: ImageData; private grassSnapshot: Uint8Array; private hazards = new Map<string, THREE.Object3D>(); private collectibles = new Map<string, THREE.Object3D>(); private animals = new Map<string, THREE.Object3D>(); private occluders: THREE.Group[] = []; private target = new THREE.Vector3();
  constructor(private host: HTMLElement, readonly engine: GameEngine) {
    this.renderer = new THREE.WebGLRenderer({ antialias: true, alpha: false, preserveDrawingBuffer: true }); this.renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); this.renderer.shadowMap.enabled = true; this.renderer.shadowMap.type = THREE.PCFSoftShadowMap; this.host.append(this.renderer.domElement);
    this.camera = new THREE.OrthographicCamera(-12, 12, 8, -8, 0.1, 100); this.camera.position.set(18, 21, 18); this.scene.background = new THREE.Color(engine.level.sky); this.scene.fog = new THREE.Fog(engine.level.sky, 34, 58); this.grassSnapshot = new Uint8Array(engine.grass.states.length);
    this.scene.add(new THREE.HemisphereLight("#eaf9ff", "#58724d", 2.1)); const sun = new THREE.DirectionalLight("#fff0cc", 3.2); sun.position.set(-12, 24, 8); sun.castShadow = true; sun.shadow.mapSize.set(1024, 1024); this.scene.add(sun); this.createWorld(); this.resize(); window.addEventListener("resize", this.resize);
  }
  private createWorld(): void {
    const level = this.engine.level; const floor = mesh(new THREE.PlaneGeometry(level.world.width + 8, level.world.depth + 8), "#4d653f"); floor.rotation.x = -Math.PI / 2; floor.position.y = -0.08; this.scene.add(floor);
    const canvas = document.createElement("canvas"); canvas.width = this.engine.grass.cols; canvas.height = this.engine.grass.rows; this.grassContext = canvas.getContext("2d")!; this.grassImage = this.grassContext.createImageData(canvas.width, canvas.height); this.paintGrass(); this.grassContext.putImageData(this.grassImage, 0, 0); this.grassTexture = new THREE.CanvasTexture(canvas); this.grassTexture.colorSpace = THREE.SRGBColorSpace; this.grassTexture.magFilter = THREE.NearestFilter; this.grassTexture.minFilter = THREE.NearestFilter; const grass = new THREE.Mesh(new THREE.PlaneGeometry(level.world.width, level.world.depth), new THREE.MeshBasicMaterial({ map: this.grassTexture, transparent: true })); grass.rotation.x = -Math.PI / 2; grass.position.y = 0.012; this.scene.add(grass);
    for (const object of level.objects) this.addObject(object); this.addMower(); for (const hazard of level.hazards) { const item = this.addHazard(hazard.type); item.position.set(hazard.position.x, 0.16, hazard.position.z); this.hazards.set(hazard.id, item); }
    for (const item of level.collectibles) { const group = new THREE.Group(); const gem = mesh(new THREE.OctahedronGeometry(0.26), "#ffd35c"); gem.rotation.x = 0.4; gem.castShadow = true; group.add(gem); const ring = new THREE.Mesh(new THREE.TorusGeometry(0.38, 0.035, 6, 16), material("#fff2b7")); ring.rotation.x = Math.PI / 2; group.add(ring); group.position.set(item.position.x, 0.36, item.position.z); this.scene.add(group); this.collectibles.set(item.id, group); }
    for (const animal of this.engine.animals) { const group = new THREE.Group(); const body = mesh(new THREE.SphereGeometry(animal.kind === "dog" ? 0.38 : 0.25, 8, 6), animal.kind === "dog" ? "#b47a52" : animal.kind === "cat" ? "#62616b" : "#a9673a"); body.scale.set(1.2, 0.8, 1); body.castShadow = true; group.add(body); const head = mesh(new THREE.SphereGeometry(0.18, 8, 6), animal.kind === "squirrel" ? "#c47e43" : "#efe6d5"); head.position.set(0, 0.1, 0.27); group.add(head); group.position.set(animal.position.x, 0.28, animal.position.z); this.scene.add(group); this.animals.set(animal.id, group); }
  }
  private addObject(object: GameEngine["level"]["objects"][number]): void {
    const group = new THREE.Group(); const { x, z } = object.position;
    if (object.type === "tree") { const trunk = mesh(new THREE.CylinderGeometry(0.3, 0.42, 2.3, 8), "#8a5e3e"); trunk.position.y = 1.12; trunk.castShadow = true; group.add(trunk); const canopy = mesh(new THREE.DodecahedronGeometry(1.55, 0), "#356d43"); canopy.name = "fade"; canopy.position.y = 3; canopy.scale.set(1, 0.8, 1); canopy.castShadow = true; group.add(canopy); this.occluders.push(group); }
    else if (object.type === "house" || object.type === "cabin") { const w = object.collider.kind === "rect" ? object.collider.width : 3; const d = object.collider.kind === "rect" ? object.collider.depth : 3; const body = mesh(new THREE.BoxGeometry(w, 2.7, d), object.color ?? "#cf765b"); body.name = "fade"; body.position.y = 1.35; body.castShadow = true; body.receiveShadow = true; group.add(body); const roof = mesh(new THREE.ConeGeometry(Math.max(w, d) * 0.77, 2.4, 4), "#7b4b48"); roof.name = "fade"; roof.position.y = 3.75; roof.rotation.y = Math.PI / 4; roof.castShadow = true; group.add(roof); group.userData.occlusionRadius = Math.max(w, d) * 0.62; this.occluders.push(group); }
    else if (object.type === "dock") { const pad = mesh(new THREE.BoxGeometry(2.2, 0.28, 1.6), object.color ?? "#60727c"); pad.position.y = 0.14; group.add(pad); const lamp = mesh(new THREE.CylinderGeometry(0.1, 0.1, 1.1, 6), "#c4e6e4"); lamp.position.set(0.72, 0.58, 0); group.add(lamp); }
    else { const w = object.collider.kind === "rect" ? object.collider.width : object.collider.radius * 2; const d = object.collider.kind === "rect" ? object.collider.depth : object.collider.radius * 2; const shape = object.type === "water" || object.type === "driveway" || object.type === "patio" || object.type === "garden" ? new THREE.BoxGeometry(w, 0.07, d) : object.type === "rock" || object.type === "firepit" ? new THREE.DodecahedronGeometry(w * 0.55, 0) : new THREE.BoxGeometry(w, 0.8, d); const item = mesh(shape, object.color ?? (object.type === "water" ? "#3c99bb" : object.type === "garden" ? "#a94e62" : "#8f8070")); item.position.y = object.type === "water" || object.type === "driveway" || object.type === "patio" || object.type === "garden" ? 0 : 0.4; item.castShadow = true; group.add(item); }
    group.position.set(x, 0, z); this.scene.add(group);
  }
  private addHazard(type: string): THREE.Object3D { const group = new THREE.Group(); const color = type === "fruit" ? "#dd6745" : type === "hose" || type === "leash" ? "#476c87" : type === "goose" ? "#e6e1d5" : "#d9a34c"; const item = type === "hose" || type === "leash" ? new THREE.Mesh(new THREE.TorusGeometry(0.48, 0.07, 6, 14), material(color)) : mesh(new THREE.DodecahedronGeometry(0.3, 0), color); item.rotation.x = Math.PI / 2; item.castShadow = true; group.add(item); const hint = new THREE.Mesh(new THREE.RingGeometry(0.42, 0.5, 16), material("#f4d568")); hint.rotation.x = -Math.PI / 2; hint.position.y = 0.02; group.add(hint); this.scene.add(group); return group; }
  private addMower(): void { const stats = this.engine.stats; const deck = mesh(new THREE.CylinderGeometry(stats.deckRadius, stats.deckRadius, 0.16, 16), "#263541"); deck.scale.z = 0.8; deck.position.y = 0.17; deck.castShadow = true; this.mower.add(deck); const bodyId = this.engine.loadout.body; const shellGeometry = bodyId === "body_rounded_shell" ? new THREE.SphereGeometry(0.67, 12, 8) : new THREE.BoxGeometry(bodyId === "body_heavy_utility" ? 1.28 : 1.08, bodyId === "body_heavy_utility" ? 0.62 : 0.52, 1.2); const shell = mesh(shellGeometry, stats.color); shell.position.y = 0.48; if (bodyId === "body_rounded_shell") shell.scale.set(1, 0.55, 0.9); shell.castShadow = true; shell.name = "shell"; this.mower.add(shell); const wheel = () => mesh(stats.tracks ? new THREE.BoxGeometry(0.18, 0.32, 1.05) : new THREE.CylinderGeometry(0.2, 0.2, 0.16, 10), "#1e282b"); for (const side of [-1, 1]) { const mobility = wheel(); mobility.position.set(side * 0.61, 0.27, 0); if (!stats.tracks) mobility.rotation.z = Math.PI / 2; mobility.castShadow = true; this.mower.add(mobility); } const glass = mesh(new THREE.BoxGeometry(0.56, 0.22, 0.42), "#c6eef4"); glass.position.set(0, 0.76, 0.05); this.mower.add(glass); const antenna = mesh(new THREE.CylinderGeometry(0.025, 0.025, 0.55, 6), "#f4d568"); antenna.position.set(0, 1.02, -0.18); this.mower.add(antenna); const outline = new THREE.Mesh(new THREE.TorusGeometry(stats.deckRadius + 0.14, 0.035, 8, 20), material("#fff5ba")); outline.rotation.x = Math.PI / 2; outline.position.y = 0.035; this.mower.add(outline); this.scene.add(this.mower); }
  private paintGrass(): void { const colors: Record<number, [number, number, number, number]> = { [GrassCellState.NonMowable]: [0, 0, 0, 0], [GrassCellState.Uncut]: [75, 151, 70, 255], [GrassCellState.Cut]: [166, 201, 106, 255] }; for (let index = 0; index < this.engine.grass.states.length; index += 1) { const pixel = index * 4; const color = colors[this.engine.grass.states[index]]; this.grassImage.data[pixel] = color[0]; this.grassImage.data[pixel + 1] = color[1]; this.grassImage.data[pixel + 2] = color[2]; this.grassImage.data[pixel + 3] = color[3]; this.grassSnapshot[index] = this.engine.grass.states[index]; } }
  resize = (): void => { const width = this.host.clientWidth || innerWidth; const height = this.host.clientHeight || innerHeight; this.renderer.setSize(width, height, false); const aspect = width / height; const vertical = innerWidth < 900 ? 8.6 : 10; this.camera.left = -vertical * aspect; this.camera.right = vertical * aspect; this.camera.top = vertical; this.camera.bottom = -vertical; this.camera.updateProjectionMatrix(); };
  sync(): void {
    const { mower, grass, level } = this.engine; this.mower.position.set(mower.position.x, 0, mower.position.z); this.mower.rotation.y = mower.angle; const shell = this.mower.getObjectByName("shell") as MaterialMesh | undefined; if (shell) shell.material.color.set(this.engine.stats.color);
    if (grass.states.some((state, index) => state !== this.grassSnapshot[index])) { this.paintGrass(); this.grassContext.putImageData(this.grassImage, 0, 0); this.grassTexture.needsUpdate = true; }
    for (const hazard of level.hazards) { const visual = this.hazards.get(hazard.id)!; const state = this.engine.hazards.get(hazard.id)!; visual.visible = state.revealed && !state.hit; visual.rotation.y += 0.015; }
    for (const collectible of level.collectibles) { const visual = this.collectibles.get(collectible.id)!; visual.visible = !this.engine.collectibles.has(collectible.id); visual.rotation.y += 0.025; visual.position.y = 0.32 + Math.sin(this.engine.state.elapsedSeconds * 3 + visual.position.x) * 0.08; }
    for (const animal of this.engine.animals) { const visual = this.animals.get(animal.id)!; visual.position.set(animal.position.x, 0.28, animal.position.z); visual.rotation.y = Math.atan2(this.engine.mower.position.x - animal.position.x, this.engine.mower.position.z - animal.position.z); }
    for (const occluder of this.occluders) { const cameraX = this.camera.position.x; const cameraZ = this.camera.position.z; const lineX = mower.position.x - cameraX; const lineZ = mower.position.z - cameraZ; const lineLengthSquared = lineX * lineX + lineZ * lineZ; const progress = ((occluder.position.x - cameraX) * lineX + (occluder.position.z - cameraZ) * lineZ) / lineLengthSquared; const closestX = cameraX + lineX * clamp(progress, 0, 1); const closestZ = cameraZ + lineZ * clamp(progress, 0, 1); const radius = Number(occluder.userData.occlusionRadius ?? 1.65); const betweenCameraAndMower = progress > 0.08 && progress < 0.94 && (occluder.position.x - closestX) ** 2 + (occluder.position.z - closestZ) ** 2 < radius ** 2; occluder.traverse((object) => { if (object.name === "fade" && object instanceof THREE.Mesh && object.material instanceof THREE.MeshStandardMaterial) { object.material.transparent = true; object.material.opacity += ((betweenCameraAndMower ? 0.3 : 1) - object.material.opacity) * 0.14; } }); }
    const boundX = level.world.width / 2 - 5; const boundZ = level.world.depth / 2 - 5; this.target.set(clamp(mower.position.x, -boundX, boundX), 0, clamp(mower.position.z, -boundZ, boundZ)); const desired = this.target.clone().add(new THREE.Vector3(17, 19, 17)); this.camera.position.lerp(desired, 0.08); this.camera.lookAt(this.target); this.renderer.render(this.scene, this.camera);
  }
  dispose(): void { window.removeEventListener("resize", this.resize); this.renderer.dispose(); this.host.replaceChildren(); }
}
